<?php
/**
 * Provides better looking theming for the Backdrop search block.
 */

/**
 * Implements hook_config_info().
 */
function better_search_config_info() {
  // If this configuration file points to one particular file, a "name" key
  // will display that exact string for that file.
  $prefixes['better_search.settings'] = array(
    'label' => t('Better Search Settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_menu().
 */
function better_search_menu() {
  $items['admin/config/search/better-search'] = array(
    'title' => t('Better search settings'),
    'description' => t('Configure the theme for the Better Search Module.'),
    'file' => 'better_search.admin.inc',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('better_search_admin_form'),
    'access arguments' => array('administer search'),
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function better_search_form_search_block_form_alter(&$form, &$form_state, $form_id) {

  $path = backdrop_get_path('module', 'better_search');
  $config = config('better_search.settings');
  // TODO This variable was probably removed in Backdrop without replacement.
  $theme = $config->get('theme');
  switch ($theme) {
    case 0:
      $form['#attached']['css'][] = $path . '/css/background_fade.css';
      break;
    case 1:
      $form['#attached']['css'][] = $path . '/css/expand_on_hover.css';
      break;
    case 2:
      $form['#attached']['css'][] = $path . '/css/increase_icon_size.css';
      break;
    case 3:
      $form['#attached']['css'][] = $path . '/css/on_hover_button.css';
      break;
  }
  if (module_exists('font_awesome')) {
    $i = '<i class="fas fa-search"></i>';
  } else {
    $i = '<i class="better_search"></i>';
  }
  if ($theme == 3) {
    $form['search_block_form']['#suffix'] = ' <button class="icon">' . $i . '</button>';
  }
  else {
    $form['search_block_form']['#prefix'] = '<div class="icon">' . $i . '</div>';
  }
  $form['search_block_form']['#attributes']['placeholder'] = t($config->get('placeholder_text'));
  $form['actions']['#attributes']['class'][] = 'element-invisible';
  $form['search_block_form']['#size'] = $config->get('size');

  // Change the color of input search text.
  backdrop_add_css('#search-block-form .form-item-search-block-form input.form-text{color:' . $config->get('placeholder_color') . '}', 'inline');
}
